version: "3.4"

services:
  app-a:
    # image: ghcr.io/blueswen/fastapi-observability/app:latest
    build:
      context: .
    volumes:
      - .:/app
    container_name: app-a
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    environment:
      APP_NAME: "app-a"
    depends_on:
      - otel-collector
    networks:
      - observability-network

  app-b:
    # image: ghcr.io/blueswen/fastapi-observability/app:latest
    build:
      context: .
    volumes:
      - .:/app
    container_name: app-b
    ports:
      - 8001:8000
    env_file:
      - .env.dev
    environment:
      APP_NAME: "app-b"
    depends_on:
      - otel-collector
    networks:
      - observability-network

  app-c:
    # image: ghcr.io/blueswen/fastapi-observability/app:latest
    build:
      context: .
    volumes:
      - .:/app
    container_name: app-c
    ports:
      - 8007:8000
    env_file:
      - .env.dev
    environment:
      APP_NAME: "app-c"
    depends_on:
      - otel-collector
    networks:
      - observability-network

  # pushgateway:
  #   container_name: pushgateway
  #   build:
  #     context: templates/pushgateway
  #   ports:
  #     - 8001:8001
  #   restart: always
  #   networks:
  #     - observability-network

  prometheus:
    container_name: prometheus
    build:
      context: templates/prometheus
    volumes:
      - ./templates/prometheus:/etc/prometheus
    ports:
      - 8002:8002
    restart: always
    networks:
      - observability-network

  tempo:
    container_name: tempo
    build:
      context: templates/tempo
    ports:
      - 8003:8003
      - 8004:8004
      - 8008:8008
    restart: always
    networks:
      - observability-network

  grafana:
    container_name: grafana
    build:
      context: templates/grafana
    ports:
      - 8005:3000
    restart: always
    networks:
      - observability-network

  loki:
    container_name: loki
    build:
      context: templates/loki
    cpus: 0.1
    mem_limit: 100m
    env_file:
      - .env.dev
    ports:
      - 8006:8006
      - 8009:8009
    restart: always
    networks:
      - observability-network

  otel-collector:
    container_name: otel-collector
    cpus: 0.1
    mem_limit: 100m
    build:
      context: templates/otelCollector
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    restart: always
    networks:
      - observability-network

networks:
  observability-network:
    external: true