version: '3.7'

services:
  appmongo:
    build: .
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./:/app/
    ports:
      - 8000:8000
    networks:
      - db-network
    depends_on:
      - db

  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: user_root
      MONGO_INITDB_ROOT_PASSWORD: pass_root
    ports:
      - 27017:27017
    volumes:
      - ./data_db/:/data/db/
    networks:
      - db-network

  locust:
    image: locustio/locust
    command: -f /locustfile.py --host=http://appmongo:8000 --web

    volumes:
      - ./locustfile.py:/locustfile.py
    ports:
      - 8089:8089
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
