global:
  scrape_interval: 10s # Defina o intervalo de raspagem para cada 15 segundos. O padrão é a cada 1 minuto.
  evaluation_interval: 10s # Avalie as regras a cada 15 segundos. O padrão é a cada 1 minuto.
  # scrape_timeout está definido como o padrão global (10s).

# Configuração do Alertmanager
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:8002"]
  
  - job_name: 'file-discovery'
    file_sd_configs:
    - files:
      - '/etc/prometheus/targets.json'

  - job_name: 'app-a'
    scrape_interval: 5s # Substitui o padrão global para este trabalho
    static_configs:
      - targets: ['app-a:8000']

  - job_name: 'app-b'
    scrape_interval: 5s # Substitui o padrão global para este trabalho
    static_configs:
      - targets: ['app-b:8000']

  - job_name: 'app-c'
    scrape_interval: 5s # Substitui o padrão global para este trabalho
    static_configs:
      - targets: ['app-c:8000']